### ISSUE TITLE
Combine kaiko-denovo and kaiko-taxonomy

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaPro#34]
Combine kaiko-denovo pipeline and kaiko-taxonomy pipeline with ease of use in mind
Labeled at small (estimated at 2 days)

@pdpiehowski @picowatt please add subtasks or let me know and I can add them

**Comment by ssarrafan** [comment]
@picowatt can you re-assign to Camilo once he accepts GH invite please?

**Comment by CamiloPosso** [comment]
Pipelines combined in [Kaiko_pipeline](https://github.com/CamiloPosso/Kaiko_pipeline).

Modifications and additions (to do):

1) Use YAML files instead of .ini files.

2) Add ability to benchmark the time (cProfile library) and memory (memory-profiler) during a run.

3) Use s3path to read and write files, this will make cloud compatibility easier.

4) Make a readme

**Comment by ssarrafan** [comment]
@CamiloPosso can this issue be closed?

**Comment by CamiloPosso** [comment]
Almost, I will close it today, just finishing up changes to path handling.

**Comment by ssarrafan** [comment]
Ok thanks @CamiloPosso 
I'll move to the current sprint if not closed by tomorrow.

**Comment by ssarrafan** [comment]
@CamiloPosso what's the status of this issue?

**Comment by CamiloPosso** [comment]
@ssarrafan I took care of the 4 changes I commented above. The readme also goes into how to set up the database files, so I would say we can close this one. 

I'm working on unit tests to then updates the python version we use.
